### PR TITLE
remove publicly visible login password

### PR DESCRIPTION
**Pull request by PeteBoucher**
Denies access to blog pending implementation of devise or another auth scheme.
http://codealia-develop.herokuapp.com/blog/posts

### CODE REVIEW

**Comment by yggie** [comment]
tests are red, could you fix these?

**Comment by PeteBoucher** [comment]
I'm just going to mark the failing tests as pending, because we have suspended this functionality pending user persistence. Are you OK with that @yggie ?

**Comment by yggie** [comment]
I think we should just close this rather than remove the authentication and add pending steps, we can move on to implementing the proper authentication, what do you think?

**Comment by PeteBoucher** [comment]
I just wanted to expedite closing this security hole, since the blog on
development site has already been (politely) hacked.

On 11 June 2014 23:28, Bryan Yap notifications@github.com wrote:

> I think we should just close this rather than remove the authentication
> and add pending steps, we can move on to implementing the proper
> authentication, what do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AgileVentures/codealia/pull/75#issuecomment-45802474.

## 

www.peteboucher.com

Help me teach girls to code:-
http://Codealia.org
@Codealia - http://facebook.com/codealia
Crowd funding: http://igg.me/at/codealia/x

**Comment by yggie** [comment]
ah ok interesting... well who knew our site attracted so much attention so early on...

**Comment by yggie** [comment]
In this case, can we just disable the new post functionality altogether? I don't think this solution will be difficult to hack again.

**Comment by sampritipanda** [comment]
That was me, I was just trying out the blog functionality and posted it for fun.

**Comment by PeteBoucher** [comment]
I should have known ;)

On 12 June 2014 09:58, Sampriti Panda notifications@github.com wrote:

> That was me, I was just trying out the blog functionality and posted it
> for fun.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AgileVentures/codealia/pull/75#issuecomment-45839880.

## 

www.peteboucher.com

Help me teach girls to code:-
http://Codealia.org
@Codealia - http://facebook.com/codealia
Crowd funding: http://igg.me/at/codealia/x

**Comment by yggie** [comment]
ah ok it was just the development site, had me a little worried there... Anyway disable the functionality altogether till a better solution comes up, and we can focus our efforts on a real solution.

**Comment by PeteBoucher** [comment]
See https://github.com/AgileVentures/codealia/pull/77

**Pull request closed without merging**
