### PR TITLE
Indegogo campaign link and widget

### PR DESCRIPTION
**Pull request by PeteBoucher**
- Uncommented crowd funding paragraph on `static_pages/donors.html.erb`
- Added totaliser widget to site homepage to drive traffic to the IndieGoGo campaign

### CODE REVIEW

**Comment by yggie** [comment]
was there a story on this? I can't seem to find it on PV. Please make sure you go through the process of creating and voting on a story for a feature like this. You guys may have agreed to do this verbally, but someone like me might miss the process, but a record of it on PV helps immensely.

Otherwise, the PR is all good to merge. I just want to be sure this is what everybody wants before I click the merge PR button.

**Comment by tochman** [comment]
I don't recall this discussion.

**Comment by PeteBoucher** [comment]
No I made this PR on my own, let's discuss it on Monday.

**Comment by PeteBoucher** [comment]
I've created a story retroactively for this feature here https://www.pivotaltracker.com/story/show/70428660

**Comment by PeteBoucher** [comment]
I'm willing to move the IndieGoGo campaign widget to the Donors page if it's not appropriate on the Homepage.

**Comment by yggie** [comment]
@PeteBoucher could you merge with the latest develop to get the build passing? So we can merge this in immediately once we accept this story.

**Comment by PeteBoucher** [comment]
@yggie merged with latest upstream develop

**Pull request merged**
